// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: basalt/v1/kv.proto

package basaltv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StepRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *RaftMessage           `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepRequest) Reset() {
	*x = StepRequest{}
	mi := &file_basalt_v1_kv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepRequest) ProtoMessage() {}

func (x *StepRequest) ProtoReflect() protoreflect.Message {
	mi := &file_basalt_v1_kv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepRequest.ProtoReflect.Descriptor instead.
func (*StepRequest) Descriptor() ([]byte, []int) {
	return file_basalt_v1_kv_proto_rawDescGZIP(), []int{0}
}

func (x *StepRequest) GetMessage() *RaftMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

type RaftMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         uint64                 `protobuf:"varint,10,opt,name=group,proto3" json:"group,omitempty"`
	Type          uint64                 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	From          uint64                 `protobuf:"varint,2,opt,name=from,proto3" json:"from,omitempty"`
	To            uint64                 `protobuf:"varint,3,opt,name=to,proto3" json:"to,omitempty"`
	Term          uint64                 `protobuf:"varint,4,opt,name=term,proto3" json:"term,omitempty"`
	LogIndex      uint64                 `protobuf:"varint,5,opt,name=log_index,json=logIndex,proto3" json:"log_index,omitempty"`
	LogTerm       uint64                 `protobuf:"varint,6,opt,name=log_term,json=logTerm,proto3" json:"log_term,omitempty"`
	Commit        uint64                 `protobuf:"varint,7,opt,name=commit,proto3" json:"commit,omitempty"`
	Reject        bool                   `protobuf:"varint,8,opt,name=reject,proto3" json:"reject,omitempty"`
	Entries       []*RaftEntry           `protobuf:"bytes,9,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftMessage) Reset() {
	*x = RaftMessage{}
	mi := &file_basalt_v1_kv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftMessage) ProtoMessage() {}

func (x *RaftMessage) ProtoReflect() protoreflect.Message {
	mi := &file_basalt_v1_kv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftMessage.ProtoReflect.Descriptor instead.
func (*RaftMessage) Descriptor() ([]byte, []int) {
	return file_basalt_v1_kv_proto_rawDescGZIP(), []int{1}
}

func (x *RaftMessage) GetGroup() uint64 {
	if x != nil {
		return x.Group
	}
	return 0
}

func (x *RaftMessage) GetType() uint64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *RaftMessage) GetFrom() uint64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *RaftMessage) GetTo() uint64 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *RaftMessage) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RaftMessage) GetLogIndex() uint64 {
	if x != nil {
		return x.LogIndex
	}
	return 0
}

func (x *RaftMessage) GetLogTerm() uint64 {
	if x != nil {
		return x.LogTerm
	}
	return 0
}

func (x *RaftMessage) GetCommit() uint64 {
	if x != nil {
		return x.Commit
	}
	return 0
}

func (x *RaftMessage) GetReject() bool {
	if x != nil {
		return x.Reject
	}
	return false
}

func (x *RaftMessage) GetEntries() []*RaftEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type RaftEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint64                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Term          uint64                 `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Type          uint64                 `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftEntry) Reset() {
	*x = RaftEntry{}
	mi := &file_basalt_v1_kv_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftEntry) ProtoMessage() {}

func (x *RaftEntry) ProtoReflect() protoreflect.Message {
	mi := &file_basalt_v1_kv_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftEntry.ProtoReflect.Descriptor instead.
func (*RaftEntry) Descriptor() ([]byte, []int) {
	return file_basalt_v1_kv_proto_rawDescGZIP(), []int{2}
}

func (x *RaftEntry) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *RaftEntry) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RaftEntry) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *RaftEntry) GetType() uint64 {
	if x != nil {
		return x.Type
	}
	return 0
}

type StepResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepResponse) Reset() {
	*x = StepResponse{}
	mi := &file_basalt_v1_kv_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepResponse) ProtoMessage() {}

func (x *StepResponse) ProtoReflect() protoreflect.Message {
	mi := &file_basalt_v1_kv_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepResponse.ProtoReflect.Descriptor instead.
func (*StepResponse) Descriptor() ([]byte, []int) {
	return file_basalt_v1_kv_proto_rawDescGZIP(), []int{3}
}

type UpdateShardMapRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Map           []byte                 `protobuf:"bytes,1,opt,name=map,proto3" json:"map,omitempty"` // marshaled ShardMap
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateShardMapRequest) Reset() {
	*x = UpdateShardMapRequest{}
	mi := &file_basalt_v1_kv_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateShardMapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateShardMapRequest) ProtoMessage() {}

func (x *UpdateShardMapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_basalt_v1_kv_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateShardMapRequest.ProtoReflect.Descriptor instead.
func (*UpdateShardMapRequest) Descriptor() ([]byte, []int) {
	return file_basalt_v1_kv_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateShardMapRequest) GetMap() []byte {
	if x != nil {
		return x.Map
	}
	return nil
}

type UpdateShardMapResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"` // false if the node already has an equal-or-higher epoch
	Epoch         uint64                 `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`       // the node's epoch after the call
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateShardMapResponse) Reset() {
	*x = UpdateShardMapResponse{}
	mi := &file_basalt_v1_kv_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateShardMapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateShardMapResponse) ProtoMessage() {}

func (x *UpdateShardMapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_basalt_v1_kv_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateShardMapResponse.ProtoReflect.Descriptor instead.
func (*UpdateShardMapResponse) Descriptor() ([]byte, []int) {
	return file_basalt_v1_kv_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateShardMapResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *UpdateShardMapResponse) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

type GetShardMapRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShardMapRequest) Reset() {
	*x = GetShardMapRequest{}
	mi := &file_basalt_v1_kv_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShardMapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShardMapRequest) ProtoMessage() {}

func (x *GetShardMapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_basalt_v1_kv_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShardMapRequest.ProtoReflect.Descriptor instead.
func (*GetShardMapRequest) Descriptor() ([]byte, []int) {
	return file_basalt_v1_kv_proto_rawDescGZIP(), []int{6}
}

type GetShardMapResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Map           []byte                 `protobuf:"bytes,1,opt,name=map,proto3" json:"map,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShardMapResponse) Reset() {
	*x = GetShardMapResponse{}
	mi := &file_basalt_v1_kv_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShardMapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShardMapResponse) ProtoMessage() {}

func (x *GetShardMapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_basalt_v1_kv_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShardMapResponse.ProtoReflect.Descriptor instead.
func (*GetShardMapResponse) Descriptor() ([]byte, []int) {
	return file_basalt_v1_kv_proto_rawDescGZIP(), []int{7}
}

func (x *GetShardMapResponse) GetMap() []byte {
	if x != nil {
		return x.Map
	}
	return nil
}

type AddGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         uint64                 `protobuf:"varint,1,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddGroupRequest) Reset() {
	*x = AddGroupRequest{}
	mi := &file_basalt_v1_kv_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddGroupRequest) ProtoMessage() {}

func (x *AddGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_basalt_v1_kv_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddGroupRequest.ProtoReflect.Descriptor instead.
func (*AddGroupRequest) Descriptor() ([]byte, []int) {
	return file_basalt_v1_kv_proto_rawDescGZIP(), []int{8}
}

func (x *AddGroupRequest) GetGroup() uint64 {
	if x != nil {
		return x.Group
	}
	return 0
}

type AddGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddGroupResponse) Reset() {
	*x = AddGroupResponse{}
	mi := &file_basalt_v1_kv_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddGroupResponse) ProtoMessage() {}

func (x *AddGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_basalt_v1_kv_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddGroupResponse.ProtoReflect.Descriptor instead.
func (*AddGroupResponse) Descriptor() ([]byte, []int) {
	return file_basalt_v1_kv_proto_rawDescGZIP(), []int{9}
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_basalt_v1_kv_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_basalt_v1_kv_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_basalt_v1_kv_proto_rawDescGZIP(), []int{10}
}

func (x *GetRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_basalt_v1_kv_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_basalt_v1_kv_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_basalt_v1_kv_proto_rawDescGZIP(), []int{11}
}

func (x *GetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type PutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_basalt_v1_kv_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_basalt_v1_kv_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_basalt_v1_kv_proto_rawDescGZIP(), []int{12}
}

func (x *PutRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *PutRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type PutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	mi := &file_basalt_v1_kv_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_basalt_v1_kv_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) {
	return file_basalt_v1_kv_proto_rawDescGZIP(), []int{13}
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_basalt_v1_kv_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_basalt_v1_kv_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_basalt_v1_kv_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_basalt_v1_kv_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_basalt_v1_kv_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_basalt_v1_kv_proto_rawDescGZIP(), []int{15}
}

type ScanRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// start is inclusive; empty means the first key.
	Start []byte `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	// end is exclusive; empty means past the last key.
	End []byte `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	// limit caps the total pairs returned; zero means unlimited.
	Limit uint64 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	// group, when non-zero, asks the addressed node to scan exactly that
	// raft group (an internal scatter-gather leg); zero is a client-facing
	// scan that the front door fans out across every group.
	Group         uint64 `protobuf:"varint,4,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanRequest) Reset() {
	*x = ScanRequest{}
	mi := &file_basalt_v1_kv_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanRequest) ProtoMessage() {}

func (x *ScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_basalt_v1_kv_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanRequest.ProtoReflect.Descriptor instead.
func (*ScanRequest) Descriptor() ([]byte, []int) {
	return file_basalt_v1_kv_proto_rawDescGZIP(), []int{16}
}

func (x *ScanRequest) GetStart() []byte {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *ScanRequest) GetEnd() []byte {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *ScanRequest) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ScanRequest) GetGroup() uint64 {
	if x != nil {
		return x.Group
	}
	return 0
}

type ScanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pairs         []*KeyValue            `protobuf:"bytes,1,rep,name=pairs,proto3" json:"pairs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanResponse) Reset() {
	*x = ScanResponse{}
	mi := &file_basalt_v1_kv_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanResponse) ProtoMessage() {}

func (x *ScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_basalt_v1_kv_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanResponse.ProtoReflect.Descriptor instead.
func (*ScanResponse) Descriptor() ([]byte, []int) {
	return file_basalt_v1_kv_proto_rawDescGZIP(), []int{17}
}

func (x *ScanResponse) GetPairs() []*KeyValue {
	if x != nil {
		return x.Pairs
	}
	return nil
}

type KeyValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyValue) Reset() {
	*x = KeyValue{}
	mi := &file_basalt_v1_kv_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValue) ProtoMessage() {}

func (x *KeyValue) ProtoReflect() protoreflect.Message {
	mi := &file_basalt_v1_kv_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValue.ProtoReflect.Descriptor instead.
func (*KeyValue) Descriptor() ([]byte, []int) {
	return file_basalt_v1_kv_proto_rawDescGZIP(), []int{18}
}

func (x *KeyValue) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *KeyValue) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_basalt_v1_kv_proto protoreflect.FileDescriptor

const file_basalt_v1_kv_proto_rawDesc = "" +
	"\n" +
	"\x12basalt/v1/kv.proto\x12\tbasalt.v1\"?\n" +
	"\vStepRequest\x120\n" +
	"\amessage\x18\x01 \x01(\v2\x16.basalt.v1.RaftMessageR\amessage\"\x87\x02\n" +
	"\vRaftMessage\x12\x14\n" +
	"\x05group\x18\n" +
	" \x01(\x04R\x05group\x12\x12\n" +
	"\x04type\x18\x01 \x01(\x04R\x04type\x12\x12\n" +
	"\x04from\x18\x02 \x01(\x04R\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\x04R\x02to\x12\x12\n" +
	"\x04term\x18\x04 \x01(\x04R\x04term\x12\x1b\n" +
	"\tlog_index\x18\x05 \x01(\x04R\blogIndex\x12\x19\n" +
	"\blog_term\x18\x06 \x01(\x04R\alogTerm\x12\x16\n" +
	"\x06commit\x18\a \x01(\x04R\x06commit\x12\x16\n" +
	"\x06reject\x18\b \x01(\bR\x06reject\x12.\n" +
	"\aentries\x18\t \x03(\v2\x14.basalt.v1.RaftEntryR\aentries\"]\n" +
	"\tRaftEntry\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x04R\x05index\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x04R\x04term\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x12\n" +
	"\x04type\x18\x04 \x01(\x04R\x04type\"\x0e\n" +
	"\fStepResponse\")\n" +
	"\x15UpdateShardMapRequest\x12\x10\n" +
	"\x03map\x18\x01 \x01(\fR\x03map\"J\n" +
	"\x16UpdateShardMapResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\x04R\x05epoch\"\x14\n" +
	"\x12GetShardMapRequest\"'\n" +
	"\x13GetShardMapResponse\x12\x10\n" +
	"\x03map\x18\x01 \x01(\fR\x03map\"'\n" +
	"\x0fAddGroupRequest\x12\x14\n" +
	"\x05group\x18\x01 \x01(\x04R\x05group\"\x12\n" +
	"\x10AddGroupResponse\"\x1e\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\"9\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"4\n" +
	"\n" +
	"PutRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"\r\n" +
	"\vPutResponse\"!\n" +
	"\rDeleteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\"\x10\n" +
	"\x0eDeleteResponse\"a\n" +
	"\vScanRequest\x12\x14\n" +
	"\x05start\x18\x01 \x01(\fR\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\fR\x03end\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x04R\x05limit\x12\x14\n" +
	"\x05group\x18\x04 \x01(\x04R\x05group\"9\n" +
	"\fScanResponse\x12)\n" +
	"\x05pairs\x18\x01 \x03(\v2\x13.basalt.v1.KeyValueR\x05pairs\"2\n" +
	"\bKeyValue\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value2\xf1\x01\n" +
	"\tKVService\x124\n" +
	"\x03Get\x12\x15.basalt.v1.GetRequest\x1a\x16.basalt.v1.GetResponse\x124\n" +
	"\x03Put\x12\x15.basalt.v1.PutRequest\x1a\x16.basalt.v1.PutResponse\x12=\n" +
	"\x06Delete\x12\x18.basalt.v1.DeleteRequest\x1a\x19.basalt.v1.DeleteResponse\x129\n" +
	"\x04Scan\x12\x16.basalt.v1.ScanRequest\x1a\x17.basalt.v1.ScanResponse0\x012F\n" +
	"\vRaftService\x127\n" +
	"\x04Step\x12\x16.basalt.v1.StepRequest\x1a\x17.basalt.v1.StepResponse2\xf8\x01\n" +
	"\fShardService\x12U\n" +
	"\x0eUpdateShardMap\x12 .basalt.v1.UpdateShardMapRequest\x1a!.basalt.v1.UpdateShardMapResponse\x12L\n" +
	"\vGetShardMap\x12\x1d.basalt.v1.GetShardMapRequest\x1a\x1e.basalt.v1.GetShardMapResponse\x12C\n" +
	"\bAddGroup\x12\x1a.basalt.v1.AddGroupRequest\x1a\x1b.basalt.v1.AddGroupResponseB4Z2github.com/LovRanRan/basalt/api/basalt/v1;basaltv1b\x06proto3"

var (
	file_basalt_v1_kv_proto_rawDescOnce sync.Once
	file_basalt_v1_kv_proto_rawDescData []byte
)

func file_basalt_v1_kv_proto_rawDescGZIP() []byte {
	file_basalt_v1_kv_proto_rawDescOnce.Do(func() {
		file_basalt_v1_kv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_basalt_v1_kv_proto_rawDesc), len(file_basalt_v1_kv_proto_rawDesc)))
	})
	return file_basalt_v1_kv_proto_rawDescData
}

var file_basalt_v1_kv_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_basalt_v1_kv_proto_goTypes = []any{
	(*StepRequest)(nil),            // 0: basalt.v1.StepRequest
	(*RaftMessage)(nil),            // 1: basalt.v1.RaftMessage
	(*RaftEntry)(nil),              // 2: basalt.v1.RaftEntry
	(*StepResponse)(nil),           // 3: basalt.v1.StepResponse
	(*UpdateShardMapRequest)(nil),  // 4: basalt.v1.UpdateShardMapRequest
	(*UpdateShardMapResponse)(nil), // 5: basalt.v1.UpdateShardMapResponse
	(*GetShardMapRequest)(nil),     // 6: basalt.v1.GetShardMapRequest
	(*GetShardMapResponse)(nil),    // 7: basalt.v1.GetShardMapResponse
	(*AddGroupRequest)(nil),        // 8: basalt.v1.AddGroupRequest
	(*AddGroupResponse)(nil),       // 9: basalt.v1.AddGroupResponse
	(*GetRequest)(nil),             // 10: basalt.v1.GetRequest
	(*GetResponse)(nil),            // 11: basalt.v1.GetResponse
	(*PutRequest)(nil),             // 12: basalt.v1.PutRequest
	(*PutResponse)(nil),            // 13: basalt.v1.PutResponse
	(*DeleteRequest)(nil),          // 14: basalt.v1.DeleteRequest
	(*DeleteResponse)(nil),         // 15: basalt.v1.DeleteResponse
	(*ScanRequest)(nil),            // 16: basalt.v1.ScanRequest
	(*ScanResponse)(nil),           // 17: basalt.v1.ScanResponse
	(*KeyValue)(nil),               // 18: basalt.v1.KeyValue
}
var file_basalt_v1_kv_proto_depIdxs = []int32{
	1,  // 0: basalt.v1.StepRequest.message:type_name -> basalt.v1.RaftMessage
	2,  // 1: basalt.v1.RaftMessage.entries:type_name -> basalt.v1.RaftEntry
	18, // 2: basalt.v1.ScanResponse.pairs:type_name -> basalt.v1.KeyValue
	10, // 3: basalt.v1.KVService.Get:input_type -> basalt.v1.GetRequest
	12, // 4: basalt.v1.KVService.Put:input_type -> basalt.v1.PutRequest
	14, // 5: basalt.v1.KVService.Delete:input_type -> basalt.v1.DeleteRequest
	16, // 6: basalt.v1.KVService.Scan:input_type -> basalt.v1.ScanRequest
	0,  // 7: basalt.v1.RaftService.Step:input_type -> basalt.v1.StepRequest
	4,  // 8: basalt.v1.ShardService.UpdateShardMap:input_type -> basalt.v1.UpdateShardMapRequest
	6,  // 9: basalt.v1.ShardService.GetShardMap:input_type -> basalt.v1.GetShardMapRequest
	8,  // 10: basalt.v1.ShardService.AddGroup:input_type -> basalt.v1.AddGroupRequest
	11, // 11: basalt.v1.KVService.Get:output_type -> basalt.v1.GetResponse
	13, // 12: basalt.v1.KVService.Put:output_type -> basalt.v1.PutResponse
	15, // 13: basalt.v1.KVService.Delete:output_type -> basalt.v1.DeleteResponse
	17, // 14: basalt.v1.KVService.Scan:output_type -> basalt.v1.ScanResponse
	3,  // 15: basalt.v1.RaftService.Step:output_type -> basalt.v1.StepResponse
	5,  // 16: basalt.v1.ShardService.UpdateShardMap:output_type -> basalt.v1.UpdateShardMapResponse
	7,  // 17: basalt.v1.ShardService.GetShardMap:output_type -> basalt.v1.GetShardMapResponse
	9,  // 18: basalt.v1.ShardService.AddGroup:output_type -> basalt.v1.AddGroupResponse
	11, // [11:19] is the sub-list for method output_type
	3,  // [3:11] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_basalt_v1_kv_proto_init() }
func file_basalt_v1_kv_proto_init() {
	if File_basalt_v1_kv_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_basalt_v1_kv_proto_rawDesc), len(file_basalt_v1_kv_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_basalt_v1_kv_proto_goTypes,
		DependencyIndexes: file_basalt_v1_kv_proto_depIdxs,
		MessageInfos:      file_basalt_v1_kv_proto_msgTypes,
	}.Build()
	File_basalt_v1_kv_proto = out.File
	file_basalt_v1_kv_proto_goTypes = nil
	file_basalt_v1_kv_proto_depIdxs = nil
}
